### ISSUE TITLE
Error: NullPointerExceptoin In: PharamacistTest.java

### ISSUE THREAD

**Issue by builde7b0b** [Jaypad07/SmartRx#14]

**Comment by builde7b0b** [comment]
Step failed
java.lang.NullPointerException: Cannot invoke "com.sei.smartrx.repository.PrescriptionRepository.save(Object)" because "this.prescriptionRepository" is null
	at com.sei.smartrx.service.PrescriptionService.addPrescription(PrescriptionService.java:93)
	at definitions.PharmacistTest.aPrescriptionExists(PharmacistTest.java:66)
	at ✽.a prescription exists(file:///C:/Users/Zoe/Desktop/GROUP/SmartRx/src/test/resources/features/Pharmacist.feature:10)

**Comment by builde7b0b** [comment]
I keep getting this error for my delete method, It's kind of ridiculous all of the things I tried but maybe I'm doing something wrong or overthinking something.

Main Files changes are PharamacistTest and PrescriptionService along with PrescriptionRepository


PharmacistTest.java
```java
@Given("a prescription exists")
    public void aPrescriptionExists() {
        // Add a prescription to the database or use a test helper method to create a prescription
        prescriptionToAdd = prescriptionService.addPrescription(new Prescription());
    }

    @When("the pharmacist deletes a prescription")
    public void thePharmacistDeletesAPrescription() {

        prescriptionService.deletePrescription(prescriptionToAdd);


    }

    @Then("the prescription is deleted")
    public void thePrescriptionIsDeleted() {
        List<Prescription> prescriptions = prescriptionService.getAllPrescriptions();
        Assert.assertFalse(prescriptions.contains(prescriptionToAdd));


    }
```

**Comment by builde7b0b** [comment]
PrescriptionService.java


```java
 public void deletePrescription(Prescription prescription) {
        // Implement the logic to delete the prescription
        prescriptionRepository.delete(prescription);
    }
```

**Comment by builde7b0b** [comment]
![Image](https://github.com/Jaypad07/SmartRx/assets/10110062/8b67c1b1-c6f7-4e79-8eb5-d7cd9e0eedcf)

**Comment by builde7b0b** [comment]
also changed this in PharmacistTest.java 
```java
   @Given("a prescription exists")
    public void aPrescriptionExists() {
        // Add a prescription to the database or use a test helper method to create a prescription
        prescriptionToAdd = prescriptionService.addPrescription(new Prescription());
    }
```

**Comment by builde7b0b** [comment]
My updated PR with Jay's changes: https://github.com/Jaypad07/SmartRx/pull/15
